export { captureAnchor } from "./capture"
export { reactComponentName } from "./component"
export { documentRect, isRendered } from "./geometry"
export type { AnchorOptions } from "./options"
export { resolveAnchor, type Confidence, type ResolveResult } from "./resolve"
export { buildCssSelector, buildPath } from "./selector"
export { isStableClass, isStableId } from "./stable"
export { pickTarget } from "./target"
export { elementText, textSimilarity } from "./text"
