/**
 * Heuristics that decide whether an id, class or attribute is a stable,
 * human-authored identifier (good for re-finding an element) or something
 * generated by a build tool or framework (changes between deploys).
 */

const TAILWIND_PREFIX =
  /^-?(m|p|mx|my|mt|mb|ml|mr|ms|me|px|py|pt|pb|pl|pr|ps|pe|w|h|min-w|max-w|min-h|max-h|size|gap|gap-x|gap-y|space-x|space-y|text|font|bg|border|border-[trblxy]|rounded|rounded-[trbl]{1,2}|shadow|flex|grid|grid-cols|grid-rows|col|col-span|row|row-span|items|justify|self|place|content|inset|inset-x|inset-y|top|left|right|bottom|start|end|z|opacity|leading|tracking|ring|ring-offset|outline|overflow|overflow-x|overflow-y|order|basis|grow|shrink|translate-x|translate-y|scale|rotate|skew|transition|duration|ease|delay|animate|cursor|select|fill|stroke|object|aspect|line-clamp|decoration|indent|align|whitespace|break|hyphens|list|columns|backdrop|blur|brightness|contrast|drop-shadow|grayscale|invert|saturate|sepia|divide|divide-x|divide-y|from|to|via|accent|caret|scroll|snap|touch|will-change|pointer-events|underline-offset|auto-cols|auto-rows|origin|mix-blend|bg-blend|box|float|clear|appearance|resize|table|sr|not-sr)(-|$)/

const TAILWIND_EXACT = new Set([
  "flex",
  "grid",
  "block",
  "inline",
  "inline-block",
  "inline-flex",
  "inline-grid",
  "hidden",
  "contents",
  "table",
  "static",
  "fixed",
  "absolute",
  "relative",
  "sticky",
  "visible",
  "invisible",
  "container",
  "truncate",
  "underline",
  "uppercase",
  "lowercase",
  "capitalize",
  "italic",
  "antialiased",
  "sr-only",
  "grow",
  "shrink",
  "isolate",
  "transform",
  "filter",
  "group",
  "peer",
  "prose",
  "dark",
  "light",
])

const GENERATED_CLASS_PATTERNS = [
  // CSS modules: Button_root__a1B2c, _root_1x2y3, root___3xKq
  /_{1,3}(?=[a-zA-Z-]*[0-9])[a-zA-Z0-9-]{5,}$/,
  /_{1,3}(?=[a-zA-Z0-9-]*[A-Z][a-zA-Z0-9-]*[A-Z])(?=[a-zA-Z0-9-]*[a-z])[a-zA-Z0-9-]{5,8}$/,
  /^_[a-zA-Z0-9]/,
  // styled-components, emotion, styled-jsx, svelte, astro, vanilla-extract
  /^(css|sc|jsx|svelte|astro|emotion|e|tw|vanilla|chakra-[a-z]+-)[-_][a-zA-Z0-9]{4,}$/,
  /^[a-z]{1,3}-(?=[a-zA-Z]*[0-9])[a-zA-Z0-9]{5,}$/,
  // State classes that toggle at runtime
  /^(is|has)-(active|open|selected|focused|hover|hovered|visible|hidden|expanded|collapsed|loading|disabled|checked|current)$/,
  /^(active|open|selected|focus|focused|hover|current|show|showing|in|fade|collapse|collapsing)$/,
]

/** Letters and digits mixed with no word structure: "x7Hk2p", "a1b2c3d". */
function looksRandom(token: string): boolean {
  if (token.length < 5) return false
  const digits = token.replace(/[^0-9]/g, "").length
  if (digits === 0) {
    // Mixed case gibberish without separators, e.g. "kQzLmX"
    return /^[a-zA-Z]{6,}$/.test(token) && /[A-Z].*[A-Z]/.test(token) && /[a-z]/.test(token) && !/^[A-Z][a-z]+([A-Z][a-z]+)+$/.test(token)
  }
  const letters = token.replace(/[^a-zA-Z]/g, "").length
  if (letters === 0) return true
  // "item-12" or "h1" are fine, "a8f3kq" is not
  if (/^[a-zA-Z]+[-_]?\d{1,3}$/.test(token)) return false
  return digits / token.length > 0.2
}

export function isUtilityClass(name: string): boolean {
  if (/[[\]:/()%!#@&*,.>+~=]/.test(name)) return true
  if (TAILWIND_EXACT.has(name)) return true
  return TAILWIND_PREFIX.test(name)
}

export function isStableClass(name: string): boolean {
  if (!name || name.length > 40) return false
  if (name.startsWith("nuni-")) return false
  if (isUtilityClass(name)) return false
  if (GENERATED_CLASS_PATTERNS.some((re) => re.test(name))) return false
  return !looksRandom(name)
}

export function stableClasses(el: Element): string[] {
  const out: string[] = []
  for (const name of Array.from(el.classList)) {
    if (isStableClass(name)) out.push(name)
    if (out.length >= 4) break
  }
  return out
}

const GENERATED_ID_PATTERNS = [
  /^:[a-zA-Z0-9]+:$/, // React useId (:r1:)
  /^«[a-zA-Z0-9]+»$/, // React 19.1 useId
  /^(radix|headlessui|mui|react-aria|rc|base-ui|mantine|chakra|reach|downshift|ember|ext|yui|ui-id|aria|mat|cdk|ng|v|vue|svelte|el|id|uid|field|input)[-_:]/i,
  /[0-9a-f]{8}-[0-9a-f]{4}-/i, // uuid
  /\d{3,}/,
]

export function isStableId(id: string): boolean {
  if (!id || id.length > 80) return false
  if (GENERATED_ID_PATTERNS.some((re) => re.test(id))) return false
  return !looksRandom(id)
}

export const TEST_ID_ATTRIBUTES = [
  "data-nuni",
  "data-testid",
  "data-test-id",
  "data-test",
  "data-cy",
  "data-qa",
] as const

export const CAPTURED_ATTRIBUTES = [
  "aria-label",
  "name",
  "href",
  "src",
  "alt",
  "placeholder",
  "title",
  "type",
  "role",
  "for",
  "value",
] as const
